### ISSUE TITLE
Required dateutil version

### ISSUE THREAD

**Issue by shadowrock** [SeanOC/sharpy#1]
Hi,

Just installed sharpy (using easy_install) and had a problem in my initial tests when trying to fetch product/billing plans. The parse_datetime method in parsers module raised the following error: TypeError: iter() returned non-iterator of type '_timelex', which originated from python_dateutil. I fixed it by installing dateutil version 1.5 instead of 2.0. So you could modify setup.py to require 1.5 version.

Thanks for the app!

**Comment by SeanOC** [comment]
Should be fixed in the latest release, thanks for the catch!
