### ISSUE TITLE
parse_invoices w None input

### ISSUE THREAD

**Issue by shadowrock** [SeanOC/sharpy#2]
I am testing changing plans and got this error:

 line 259, in parse_invoices
    for invoice_element in invoices_element:
TypeError: 'NoneType' object is not iterable

I fixed it similarly to parse_plans method:

```
    if invoices_element:
        for invoice_element in invoices_element:
            invoices.append(self.parse_invoice(invoice_element))
```

**Comment by SeanOC** [comment]
Fixed in 0.6.9 (saaspire@c87118a45746f5f697e1df35a62a203cc7da5814)
