### ISSUE TITLE
Customer update()

### ISSUE THREAD

**Issue by shadowrock** [SeanOC/sharpy#3]
was giving me 
line 120, in make_request
    raise exception_class(response, content)
BadRequest: 400 () Bad Request - Request invalid -- need post

It seems the update method was missing: method = 'POST',

**Comment by SeanOC** [comment]
Passing a value to the method parameter isn't necessary as the Customer.update() method passes a value for the data parameter.  Given that in the cheddar API, the only method which makes sense with a data value is POST, the make_request method automatically sets the request method to POST when a value is passed for data (see [line 78](https://github.com/Saaspire/sharpy/blob/master/sharpy/client.py#L78) of client.py).

If you could provide more details on how exactly to replicate the error, or even better if you could provide a failing unittest illustrating the error you are seeing, I'd be happy to look into it.

**Comment by shadowrock** [comment]
Ok, I'll try to replicate this.

**Comment by SeanOC** [comment]
Closing this issue until it can be replicated.  Feel free to re-open with more information
